/* Glossar (bilingual DE/EN in einer Datei). GLOSSARY. Accessor GL(o,feld) in screens.js.
   Jeder Begriff: t/t_en (Begriff), r (R-Level), lz (Deeplink), d/d_en (Definition), m/m_en (Merksatz), ex/ex_en (Beispiel). */
const GLOSSARY = {
 intro_de: "<p>Prägnante Definitionen der wichtigsten Begriffe – jeweils mit <strong>Merksatz</strong> und <strong>Beispiel</strong>. R-Level ist markiert (R1 sicher prüfungsrelevant, R2 möglich, R3 nicht prüfungsrelevant, aber berufsüblich). Filtern nach R-Level oben, oder über <strong>„🃏 Begriffe lernen“</strong> als Karteikarten mit Wiedervorlage pauken.</p>",
 intro_en: "<p>Concise definitions of the most important terms – each with a <strong>mnemonic</strong> and an <strong>example</strong>. The R-level is marked (R1 definitely exam-relevant, R2 possible, R3 not exam-relevant but common in practice). Filter by R-level above, or drill them via <strong>„🃏 Study terms“</strong> as flashcards with spaced repetition.</p>",
 categories: [
  { cat:"Grundbegriffe", cat_en:"Basic concepts", terms:[
   { t:"Softwarearchitektur", t_en:"Software architecture", r:"R1", lz:"01-01",
     d:"Die grundlegenden Strukturen eines Systems: seine Bausteine, deren Beziehungen und die tragenden Entwurfsentscheidungen, deren spätere Änderung teuer ist.",
     d_en:"The fundamental structures of a system: its building blocks, their relationships, and the load-bearing design decisions whose later change is expensive.",
     m:"Bausteine + Beziehungen + tragende Entscheidungen.", m_en:"Building blocks + relationships + load-bearing decisions.",
     ex:"z. B. die Entscheidung „3-Schichten mit getrennter Datenbank“ prägt das ganze System.", ex_en:"e.g. the decision „3 layers with a separate database“ shapes the whole system." },
   { t:"Baustein", t_en:"Building block", r:"R1", lz:"01-01",
     d:"Oberbegriff für einen abgegrenzten Teil des Systems mit klarer Verantwortlichkeit. Eine Komponente ist eine speziellere Form davon.",
     d_en:"Umbrella term for a delimited part of the system with a clear responsibility. A component is a more specific form of it.",
     m:"Abgegrenzter Systemteil mit einer Aufgabe.", m_en:"A delimited system part with one task.",
     ex:"z. B. „Rechnungsmodul“, „Benutzerverwaltung“.", ex_en:"e.g. „invoicing module“, „user management“." },
   { t:"Komponente", t_en:"Component", r:"R1", lz:"01-01",
     d:"Ein Baustein mit klar definierten, vertraglich beschriebenen Schnittstellen, der über diese genutzt und ausgetauscht werden kann.",
     d_en:"A building block with clearly defined, contractually described interfaces, used and replaceable through them.",
     m:"Baustein mit vertraglicher Schnittstelle.", m_en:"Building block with a contractual interface.",
     ex:"z. B. ein Zahlungs-Service, der hinter seiner Schnittstelle austauschbar ist.", ex_en:"e.g. a payment service that is replaceable behind its interface." },
   { t:"Schnittstelle", t_en:"Interface", r:"R1", lz:"01-01",
     d:"Der nach außen sichtbare Vertrag eines Bausteins: angebotene Operationen samt Zusicherungen. Verbirgt die interne Umsetzung.",
     d_en:"The externally visible contract of a building block: offered operations with assurances. Hides the internal realization.",
     m:"Der Vertrag nach außen – das WAS, nicht das WIE.", m_en:"The outward contract – the WHAT, not the HOW.",
     ex:"z. B. „getInvoice(id): Invoice“ – wie es intern rechnet, bleibt verborgen.", ex_en:"e.g. „getInvoice(id): Invoice“ – how it computes internally stays hidden." },
   { t:"Vertrag (Contract)", t_en:"Contract", r:"R1", lz:"03-07",
     d:"Die verbindliche Zusicherung einer Schnittstelle: welche Operationen es gibt, mit welchen Vor- und Nachbedingungen. Nutzer verlassen sich nur darauf.",
     d_en:"The binding assurance of an interface: which operations exist, with which pre- and post-conditions. Users rely only on it.",
     m:"Worauf man sich verlassen darf – der Rest ist austauschbar.", m_en:"What you may rely on – the rest is replaceable.",
     ex:"z. B. „Betrag muss > 0 sein“ (Vorbedingung), „liefert Buchungsnummer“ (Nachbedingung).", ex_en:"e.g. „amount must be > 0“ (precondition), „returns a booking number“ (postcondition)." },
   { t:"Blackbox", t_en:"Black box", r:"R1", lz:"01-01",
     d:"Sicht auf einen Baustein nur von außen: Schnittstelle und Verantwortung, ohne inneren Aufbau.",
     d_en:"View of a building block from the outside only: interface and responsibility, without internal structure.",
     m:"Nur außen: Schnittstelle + Aufgabe.", m_en:"Outside only: interface + task.",
     ex:"z. B. „Zahlungsmodul: nimmt Zahlung entgegen“ – ohne zu zeigen, wie.", ex_en:"e.g. „payment module: accepts payment“ – without showing how." },
   { t:"Whitebox", t_en:"White box", r:"R1", lz:"01-01",
     d:"Sicht auf einen Baustein mit innerem Aufbau: die enthaltenen Unterbausteine und ihr Zusammenspiel. Muss zur Blackbox-Sicht konsistent sein.",
     d_en:"View of a building block including its internal structure: the contained sub-blocks and their interplay. Must be consistent with the black-box view.",
     m:"Deckel auf: der innere Aufbau.", m_en:"Lid off: the internal structure.",
     ex:"z. B. das Zahlungsmodul innen: Validierung → Provider-Adapter → Buchung.", ex_en:"e.g. the payment module inside: validation → provider adapter → booking." },
   { t:"Verantwortlichkeit", t_en:"Responsibility", r:"R1", lz:"01-01",
     d:"Die klar umrissene Aufgabe eines Bausteins (das WAS), nicht die konkrete Umsetzung (das WIE).",
     d_en:"The clearly delimited task of a building block (the WHAT), not the concrete realization (the HOW).",
     m:"Eine Aufgabe pro Baustein – klar umrissen.", m_en:"One task per building block – clearly delimited.",
     ex:"z. B. „ist zuständig für die Preisberechnung“ – nicht auch noch fürs Logging.", ex_en:"e.g. „responsible for price calculation“ – not also for logging." }
  ]},
  { cat:"Sichten", cat_en:"Views", terms:[
   { t:"Kontextsicht", t_en:"Context view", r:"R1", lz:"04-05",
     d:"Zeigt das System als Blackbox mit seinen externen Nachbarn und Schnittstellen – fachlich und technisch. Grenzt System von Umgebung ab.",
     d_en:"Shows the system as a black box with its external neighbours and interfaces – business and technical. Delimits it from its environment.",
     m:"System + Außenwelt: Wer redet mit wem?", m_en:"System + outside world: who talks to whom?",
     ex:"z. B. Shop-System ↔ Zahlungsdienstleister, Versand-API, Kunde.", ex_en:"e.g. shop system ↔ payment provider, shipping API, customer." },
   { t:"Bausteinsicht", t_en:"Building block view", r:"R1", lz:"04-05",
     d:"Die statische Zerlegung des Systems in Bausteine und ihre Beziehungen; hierarchisch verfeinerbar.",
     d_en:"The static decomposition of the system into building blocks and their relationships; hierarchically refinable.",
     m:"Statischer Aufbau: woraus besteht das System?", m_en:"Static structure: what is the system made of?",
     ex:"z. B. UI-Schicht, Fachlogik, Datenzugriff und ihre Abhängigkeiten.", ex_en:"e.g. UI layer, business logic, data access and their dependencies." },
   { t:"Laufzeitsicht", t_en:"Runtime view", r:"R1", lz:"04-05",
     d:"Das dynamische Zusammenspiel der Bausteine in ausgewählten Szenarien (z. B. Sequenzdiagramm) – nicht für alle Abläufe.",
     d_en:"The dynamic interplay of the building blocks in selected scenarios (e.g. a sequence diagram) – not for every flow.",
     m:"Dynamik: wie spielen Bausteine zusammen?", m_en:"Dynamics: how do building blocks interact?",
     ex:"z. B. Ablauf „Bestellung aufgeben“ über UI → Fachlogik → Zahlung.", ex_en:"e.g. the „place order“ flow across UI → logic → payment." },
   { t:"Verteilungssicht", t_en:"Deployment view", r:"R1", lz:"04-05",
     d:"Die Hardware-/Infrastruktur und die Abbildung der Software-Artefakte auf Knoten samt Kommunikationswegen.",
     d_en:"The hardware/infrastructure and the mapping of software artifacts onto nodes, with communication paths.",
     m:"Wo läuft was auf welcher Hardware?", m_en:"What runs where, on which hardware?",
     ex:"z. B. Web-App auf zwei App-Servern, DB auf eigenem Datenbankserver.", ex_en:"e.g. web app on two app servers, DB on its own database server." }
  ]},
  { cat:"Entwurfsprinzipien", cat_en:"Design principles", terms:[
   { t:"Modularisierung", t_en:"Modularization", r:"R1", lz:"03-04",
     d:"Zerlegung des Systems in überschaubare, möglichst unabhängige Bausteine mit klaren Zuständigkeiten – das wichtigste Struktur-Prinzip.",
     d_en:"Decomposing the system into manageable, largely independent building blocks with clear responsibilities – the most important structural principle.",
     m:"Teile und herrsche: kleine, klare Bausteine.", m_en:"Divide and conquer: small, clear building blocks.",
     ex:"z. B. Bestellung, Bezahlung, Versand als getrennte Module statt ein Monolith-Klumpen.", ex_en:"e.g. order, payment, shipping as separate modules instead of one lump." },
   { t:"Information Hiding", t_en:"Information hiding", r:"R1", lz:"03-04",
     d:"Voraussichtlich änderliche Entwurfsentscheidungen werden hinter einer stabilen Schnittstelle verborgen, sodass Änderungen lokal bleiben (Parnas).",
     d_en:"Likely-to-change design decisions are hidden behind a stable interface so that changes stay local (Parnas).",
     m:"Verstecke, was sich ändern wird.", m_en:"Hide what is likely to change.",
     ex:"z. B. das konkrete DB-Schema hinter einer Repository-Schnittstelle verbergen.", ex_en:"e.g. hide the concrete DB schema behind a repository interface." },
   { t:"Separation of Concerns", t_en:"Separation of concerns", r:"R1", lz:"03-04",
     d:"Verschiedene Belange (Fachlogik, Persistenz, UI …) werden getrennt und je einem zuständigen Baustein zugeordnet, statt sie zu vermischen.",
     d_en:"Different concerns (business logic, persistence, UI …) are separated and each assigned to a responsible building block, not mixed.",
     m:"Ein Belang, ein Ort.", m_en:"One concern, one place.",
     ex:"z. B. keine SQL-Abfragen direkt im UI-Code.", ex_en:"e.g. no SQL queries directly in the UI code." },
   { t:"Abstraktion", t_en:"Abstraction", r:"R2", lz:"03-04",
     d:"Zweckmäßiges Weglassen von Details: Bausteine hängen von Abstraktionen (Schnittstellen) ab, nicht von konkreten Implementierungen.",
     d_en:"Purposeful omission of detail: building blocks depend on abstractions (interfaces), not concrete implementations.",
     m:"Vom Konkreten aufs Wesentliche.", m_en:"From the concrete to the essential.",
     ex:"z. B. Code nutzt „Logger“ (Abstraktion), egal ob Datei- oder Cloud-Logger.", ex_en:"e.g. code uses „Logger“ (abstraction), be it a file or cloud logger." },
   { t:"Kohäsion", t_en:"Cohesion", r:"R1", lz:"03-04",
     d:"Maß dafür, wie stark die Elemente eines Bausteins zusammengehören. Hoch ist erwünscht: ein Baustein tut genau eine zusammenhängende Sache.",
     d_en:"A measure of how strongly the elements of a building block belong together. High is desirable: a block does one coherent thing.",
     m:"Was zusammengehört, gehört zusammen (hoch = gut).", m_en:"What belongs together stays together (high = good).",
     ex:"z. B. ein Rechnungsmodul enthält nur Rechnungslogik – keine Nutzerverwaltung.", ex_en:"e.g. an invoicing module contains only invoicing logic – no user management." },
   { t:"Kopplung", t_en:"Coupling", r:"R1", lz:"03-06",
     d:"Maß für die Abhängigkeit zwischen Bausteinen. Ziel: so gering wie möglich, aber so stark wie fachlich nötig.",
     d_en:"A measure of dependency between building blocks. Aim: as low as possible, but as strong as functionally necessary.",
     m:"Abhängigkeit zwischen Bausteinen (niedrig = gut).", m_en:"Dependency between blocks (low = good).",
     ex:"z. B. Modul A ruft 20 interne Methoden von B auf = enge Kopplung.", ex_en:"e.g. module A calls 20 internal methods of B = tight coupling." },
   { t:"Lose Kopplung", t_en:"Loose coupling", r:"R1", lz:"03-06",
     d:"Geringe, gut umschriebene Abhängigkeit zwischen Bausteinen. Senkt die Auswirkung von Änderungen und erleichtert isoliertes Testen.",
     d_en:"Low, well-defined dependency between building blocks. Reduces the impact of changes and eases isolated testing.",
     m:"Wenig Abhängigkeit = leicht änderbar/testbar.", m_en:"Little dependency = easy to change/test.",
     ex:"z. B. Module reden nur über eine schmale Schnittstelle oder Events.", ex_en:"e.g. modules talk only via a narrow interface or events." },
   { t:"Afferente/efferente Kopplung", t_en:"Afferent/efferent coupling", r:"R2", lz:"03-06",
     d:"Afferent = eingehende Abhängigkeiten (andere nutzen diesen Baustein → „stabil“, teuer änderbar). Efferent = ausgehende (dieser nutzt andere → „instabil“).",
     d_en:"Afferent = incoming dependencies (others use this block → „stable“, expensive to change). Efferent = outgoing (this uses others → „instable“).",
     m:"Afferent = rein, efferent = raus.", m_en:"Afferent = in, efferent = out.",
     ex:"z. B. eine zentrale Utility-Bibliothek hat viele afferente Abhängigkeiten.", ex_en:"e.g. a central utility library has many afferent dependencies." },
   { t:"Statische vs. dynamische Kopplung", t_en:"Static vs. dynamic coupling", r:"R1", lz:"03-06",
     d:"Statisch = zur Übersetzungszeit sichtbar (Referenzen im Code). Dynamisch = erst zur Laufzeit (z. B. über Nachrichten). Dynamisch versteckt Kopplung oft nur.",
     d_en:"Static = visible at compile time (code references). Dynamic = only at runtime (e.g. via messages). Dynamic often merely hides coupling.",
     m:"Dynamisch ≠ automatisch lose.", m_en:"Dynamic ≠ automatically loose.",
     ex:"z. B. zwei Services über Events: fachlich hängen sie trotzdem voneinander ab.", ex_en:"e.g. two services via events: they still depend on each other functionally." },
   { t:"Open/Closed-Prinzip", t_en:"Open/closed principle", r:"R1", lz:"03-06",
     d:"Ein Baustein soll offen für Erweiterung, aber geschlossen für Änderung sein: neues Verhalten durch Hinzufügen, nicht durch Umbauen des Bestehenden.",
     d_en:"A building block should be open for extension but closed for modification: new behaviour by adding, not by changing the existing.",
     m:"Erweitern statt ändern.", m_en:"Extend, don't modify.",
     ex:"z. B. neue Zahlart als neue Klasse ergänzen, statt bestehenden Code umzubauen.", ex_en:"e.g. add a new payment type as a new class instead of editing existing code." },
   { t:"Dependency-Inversion-Prinzip", t_en:"Dependency inversion principle", r:"R1", lz:"03-06",
     d:"High- und Low-Level-Module hängen von gemeinsamen Abstraktionen ab; Details hängen von Abstraktionen ab, nicht umgekehrt.",
     d_en:"High- and low-level modules depend on shared abstractions; details depend on abstractions, not the other way around.",
     m:"Alle hängen an der Abstraktion, nicht am Detail.", m_en:"Everyone depends on the abstraction, not the detail.",
     ex:"z. B. Fachlogik kennt nur „Repository“, nicht „MySQL-Repository“.", ex_en:"e.g. business logic knows only „Repository“, not „MySQL repository“." },
   { t:"Single-Responsibility-Prinzip (SRP)", t_en:"Single responsibility principle (SRP)", r:"R3", lz:"03-04",
     d:"Ein Baustein sollte nur einen einzigen Grund haben, sich zu ändern – also genau eine Verantwortlichkeit.",
     d_en:"A building block should have only one reason to change – i.e. exactly one responsibility.",
     m:"Ein Grund zur Änderung.", m_en:"One reason to change.",
     ex:"z. B. eine Klasse berechnet ODER formatiert – nicht beides.", ex_en:"e.g. a class calculates OR formats – not both." },
   { t:"Interface-Segregation-Prinzip (ISP)", t_en:"Interface segregation principle (ISP)", r:"R3", lz:"03-04",
     d:"Schmale, rollenspezifische Schnittstellen, damit Clients nicht von Methoden abhängen, die sie gar nicht nutzen.",
     d_en:"Narrow, role-specific interfaces so clients don't depend on methods they don't use.",
     m:"Kleine Schnittstellen statt Alleskönner.", m_en:"Small interfaces, not do-it-all ones.",
     ex:"z. B. „Drucker“ und „Scanner“ getrennt statt einer „Multifunktions“-Schnittstelle.", ex_en:"e.g. separate „Printer“ and „Scanner“ instead of one „multifunction“ interface." },
   { t:"Liskovsches Substitutionsprinzip (LSP)", t_en:"Liskov substitution principle (LSP)", r:"R3", lz:"03-04",
     d:"Objekte eines Subtyps müssen anstelle ihres Basistyps verwendbar sein, ohne die Korrektheit des Programms zu brechen.",
     d_en:"Objects of a subtype must be usable in place of their base type without breaking the program's correctness.",
     m:"Untertyp muss den Obertyp ersetzen können.", m_en:"A subtype must be able to replace its base type.",
     ex:"z. B. „Quadrat erbt von Rechteck“ bricht oft das LSP.", ex_en:"e.g. „Square extends Rectangle“ often breaks LSP." },
   { t:"SOLID", t_en:"SOLID", r:"R3", lz:"03-04",
     d:"Sammelbegriff für fünf objektorientierte Entwurfsprinzipien: SRP, Open/Closed, LSP, ISP, DIP.",
     d_en:"Umbrella term for five object-oriented design principles: SRP, Open/Closed, LSP, ISP, DIP.",
     m:"SRP · OCP · LSP · ISP · DIP.", m_en:"SRP · OCP · LSP · ISP · DIP.",
     ex:"z. B. Merkhilfe für gut wartbaren OO-Code.", ex_en:"e.g. a checklist for maintainable OO code." },
   { t:"DRY", t_en:"DRY", r:"R3", lz:"03-04",
     d:"„Don't Repeat Yourself“: Jedes Stück Wissen bzw. jede Entscheidung hat genau eine eindeutige, autoritative Stelle im System.",
     d_en:"„Don't Repeat Yourself“: each piece of knowledge or decision has exactly one authoritative place in the system.",
     m:"Wissen nur einmal repräsentieren.", m_en:"Represent knowledge only once.",
     ex:"z. B. Steuersatz an einer Stelle definieren, nicht in fünf Klassen kopieren.", ex_en:"e.g. define the tax rate in one place, not copied across five classes." },
   { t:"KISS", t_en:"KISS", r:"R3", lz:"03-04",
     d:"„Keep It Simple, Stupid“: die einfachste tragfähige Lösung bevorzugen, unnötige Komplexität vermeiden.",
     d_en:"„Keep It Simple, Stupid“: prefer the simplest viable solution, avoid unnecessary complexity.",
     m:"So einfach wie möglich.", m_en:"As simple as possible.",
     ex:"z. B. keine Plugin-Architektur bauen, wenn es nie Plugins geben wird.", ex_en:"e.g. don't build a plugin architecture if there will never be plugins." },
   { t:"YAGNI", t_en:"YAGNI", r:"R3", lz:"03-04",
     d:"„You Aren't Gonna Need It“: keine Funktionalität auf Vorrat bauen, die aktuell nicht gebraucht wird.",
     d_en:"„You Aren't Gonna Need It“: don't build functionality on spec that isn't needed now.",
     m:"Nichts auf Vorrat bauen.", m_en:"Don't build on spec.",
     ex:"z. B. keine „für später“ gedachte Multi-Währungs-Logik ohne Anforderung.", ex_en:"e.g. no „for later“ multi-currency logic without a requirement." },
   { t:"Principle of Least Astonishment (POLA)", t_en:"Principle of least astonishment (POLA)", r:"R3", lz:"03-04",
     d:"Ein System soll sich so verhalten, wie Nutzer es vernünftigerweise erwarten – keine Überraschungen.",
     d_en:"A system should behave the way users reasonably expect – no surprises.",
     m:"Erwartungskonform statt überraschend.", m_en:"Meet expectations, don't surprise.",
     ex:"z. B. „Speichern“ speichert – und löscht nicht nebenbei etwas.", ex_en:"e.g. „Save“ saves – and doesn't quietly delete something too." },
   { t:"Robustheitsgrundsatz (Postel's Law)", t_en:"Robustness principle (Postel's law)", r:"R2", lz:"03-04",
     d:"„Sei konservativ in dem, was du sendest, und großzügig in dem, was du akzeptierst.“ Erhöht die Widerstandsfähigkeit von Schnittstellen.",
     d_en:"„Be conservative in what you send, liberal in what you accept.“ Increases the robustness of interfaces.",
     m:"Streng senden, tolerant empfangen.", m_en:"Send strictly, accept liberally.",
     ex:"z. B. eine API akzeptiert optionale Felder tolerant, liefert aber sauber definierte Antworten.", ex_en:"e.g. an API tolerantly accepts optional fields but returns cleanly defined responses." },
   { t:"Konzeptionelle Integrität", t_en:"Conceptual integrity", r:"R2", lz:"03-04",
     d:"Gleichartige Probleme werden im ganzen System gleichartig gelöst (Homogenität/Konsistenz) – das macht ein System vorhersehbar.",
     d_en:"Similar problems are solved similarly throughout the system (homogeneity/consistency) – making it predictable.",
     m:"Überall gleich gedacht.", m_en:"Consistent thinking throughout.",
     ex:"z. B. überall dasselbe Fehler- und Logging-Konzept statt fünf verschiedene.", ex_en:"e.g. the same error and logging concept everywhere, not five different ones." }
  ]},
  { cat:"Architektur- & Entwurfsmuster", cat_en:"Architecture & design patterns", terms:[
   { t:"Schichten (Layer)", t_en:"Layers", r:"R1", lz:"03-08",
     d:"Gliederung in übereinanderliegende Schichten; höhere nutzen tiefere (UI → Fachlogik → Datenzugriff). Fördert Austauschbarkeit, kann Latenz kosten.",
     d_en:"Structure into stacked layers; higher use lower (UI → business logic → data access). Promotes replaceability, can cost latency.",
     m:"Übereinander gestapelt, oben nutzt unten.", m_en:"Stacked; upper uses lower.",
     ex:"z. B. klassische 3-Schichten-Webanwendung.", ex_en:"e.g. a classic 3-tier web application." },
   { t:"Pipes und Filter", t_en:"Pipes and filters", r:"R1", lz:"03-08",
     d:"Verarbeitung in unabhängigen Schritten (Filter), verbunden durch Datenströme (Pipes). Gut für mehrstufige Datenverarbeitung.",
     d_en:"Processing in independent steps (filters) connected by data streams (pipes). Good for multi-stage data processing.",
     m:"Fließband: Filter über Datenströme verkettet.", m_en:"Assembly line: filters chained by data streams.",
     ex:"z. B. Unix-Pipe „cat | grep | sort“ oder eine ETL-Datenpipeline.", ex_en:"e.g. the Unix pipe „cat | grep | sort“ or an ETL data pipeline." },
   { t:"Microservices", t_en:"Microservices", r:"R1", lz:"03-08",
     d:"Fachlich geschnittene, unabhängig deploybare Dienste. Hohe Flexibilität, aber betriebliche und verteilte Komplexität; zu feiner Schnitt (Nano) schadet.",
     d_en:"Business-cut, independently deployable services. High flexibility but operational and distributed complexity; overly fine cuts (nano) hurt.",
     m:"Kleine, unabhängig deploybare Fachdienste.", m_en:"Small, independently deployable business services.",
     ex:"z. B. getrennte Services für Katalog, Warenkorb, Bezahlung.", ex_en:"e.g. separate services for catalog, cart, payment." },
   { t:"Ports and Adapters (Hexagonal)", t_en:"Ports and adapters (hexagonal)", r:"R3", lz:"03-08",
     d:"Der fachliche Kern wird über „Ports“ von der Außenwelt entkoppelt; „Adapter“ verbinden ihn mit Technik (DB, UI, Netz). Auch Onion/Clean Architecture.",
     d_en:"The business core is decoupled from the outside via „ports“; „adapters“ connect it to technology (DB, UI, network). Also Onion/Clean Architecture.",
     m:"Fachkern innen, Technik als austauschbare Adapter außen.", m_en:"Business core inside, technology as replaceable adapters outside.",
     ex:"z. B. derselbe Kern läuft mit einem REST-Adapter und einem CLI-Adapter.", ex_en:"e.g. the same core runs with a REST adapter and a CLI adapter." },
   { t:"Adapter", t_en:"Adapter", r:"R3", lz:"03-09",
     d:"Übersetzt zwischen einer erwarteten und einer vorhandenen (inkompatiblen) Schnittstelle, ohne beide zu ändern.",
     d_en:"Translates between an expected and an existing (incompatible) interface without changing either.",
     m:"Steckdosenadapter zwischen zwei Schnittstellen.", m_en:"A plug adapter between two interfaces.",
     ex:"z. B. Adapter übersetzt die Zahlungs-API des Anbieters in die vom System erwartete.", ex_en:"e.g. an adapter maps the provider's payment API to the one the system expects." },
   { t:"Facade", t_en:"Facade", r:"R3", lz:"03-09",
     d:"Bietet einen vereinfachten, einheitlichen Zugang zu einem komplexeren Subsystem.",
     d_en:"Provides a simplified, unified access to a more complex subsystem.",
     m:"Eine einfache Tür zum komplexen Innenleben.", m_en:"One simple door to complex internals.",
     ex:"z. B. „bestelle(Warenkorb)“ verbirgt Lager-, Zahlungs- und Versandaufrufe.", ex_en:"e.g. „order(cart)“ hides inventory, payment and shipping calls." },
   { t:"Proxy", t_en:"Proxy", r:"R3", lz:"03-09",
     d:"Ein Stellvertreter mit gleicher Schnittstelle wie das Original, der Zugriffe kontrolliert (z. B. Caching, Rechte, Remote-Zugriff).",
     d_en:"A stand-in with the same interface as the original that controls access (e.g. caching, permissions, remote access).",
     m:"Stellvertreter mit gleicher Schnittstelle.", m_en:"Stand-in with the same interface.",
     ex:"z. B. ein Caching-Proxy vor einem langsamen Dienst.", ex_en:"e.g. a caching proxy in front of a slow service." },
   { t:"Observer (Beobachter)", t_en:"Observer", r:"R3", lz:"03-09",
     d:"Ein Objekt (Subject) benachrichtigt registrierte Beobachter automatisch über Zustandsänderungen – lose gekoppelt.",
     d_en:"A subject automatically notifies registered observers about state changes – loosely coupled.",
     m:"Ändere dich → alle Abonnenten werden benachrichtigt.", m_en:"Change → all subscribers get notified.",
     ex:"z. B. UI-Elemente aktualisieren sich, wenn sich das Datenmodell ändert.", ex_en:"e.g. UI elements refresh when the data model changes." },
   { t:"Strategy (Strategie)", t_en:"Strategy", r:"R3", lz:"03-09",
     d:"Ein austauschbarer Algorithmus wird hinter einer gemeinsamen Schnittstelle gekapselt und zur Laufzeit gewählt.",
     d_en:"An interchangeable algorithm is encapsulated behind a common interface and chosen at runtime.",
     m:"Verschiedene Verfahren, gleiche Schnittstelle.", m_en:"Different algorithms, same interface.",
     ex:"z. B. austauschbare Sortier- oder Preis-Strategien.", ex_en:"e.g. interchangeable sorting or pricing strategies." },
   { t:"Template Method", t_en:"Template method", r:"R3", lz:"03-09",
     d:"Eine Oberklasse gibt das Ablaufgerüst vor; Unterklassen füllen einzelne Schritte aus.",
     d_en:"A superclass defines the skeleton of an algorithm; subclasses fill in individual steps.",
     m:"Gerüst oben, Details unten.", m_en:"Skeleton on top, details below.",
     ex:"z. B. „Bericht erzeugen“ fix, aber „Daten laden“ je Unterklasse verschieden.", ex_en:"e.g. „generate report“ is fixed, but „load data“ differs per subclass." },
   { t:"Broker", t_en:"Broker", r:"R3", lz:"03-08",
     d:"Ein Vermittler entkoppelt Sender und Empfänger und leitet Anfragen/Nachrichten weiter (z. B. Message-Broker).",
     d_en:"A mediator decouples sender and receiver and forwards requests/messages (e.g. a message broker).",
     m:"Vermittler zwischen Sender und Empfänger.", m_en:"A mediator between sender and receiver.",
     ex:"z. B. Kafka/RabbitMQ zwischen Services.", ex_en:"e.g. Kafka/RabbitMQ between services." },
   { t:"CQRS", t_en:"CQRS", r:"R3", lz:"03-08",
     d:"„Command Query Responsibility Segregation“: Lese- und Schreibpfad werden getrennt modelliert (und ggf. skaliert).",
     d_en:"„Command Query Responsibility Segregation“: read and write paths are modeled (and possibly scaled) separately.",
     m:"Lesen und Schreiben getrennt.", m_en:"Separate reading and writing.",
     ex:"z. B. optimiertes Lesemodell getrennt vom Schreibmodell.", ex_en:"e.g. an optimized read model separate from the write model." },
   { t:"Event Sourcing", t_en:"Event sourcing", r:"R3", lz:"03-08",
     d:"Der Zustand wird nicht direkt gespeichert, sondern als Folge von Ereignissen; der aktuelle Zustand ergibt sich durch Abspielen der Events.",
     d_en:"State is not stored directly but as a sequence of events; the current state results from replaying the events.",
     m:"Nicht den Stand, sondern alle Änderungen speichern.", m_en:"Store the changes, not the current state.",
     ex:"z. B. Kontostand = Summe aller Buchungs-Events.", ex_en:"e.g. account balance = sum of all booking events." },
   { t:"MVC (Model-View-Controller)", t_en:"MVC (model-view-controller)", r:"R3", lz:"03-08",
     d:"Trennt Datenmodell, Darstellung (View) und Steuerung/Interaktion (Controller).",
     d_en:"Separates data model, presentation (view) and control/interaction (controller).",
     m:"Modell · Ansicht · Steuerung.", m_en:"Model · view · controller.",
     ex:"z. B. Web-Framework mit Model, HTML-View und Controller.", ex_en:"e.g. a web framework with model, HTML view and controller." },
   { t:"Publish/Subscribe", t_en:"Publish/subscribe", r:"R3", lz:"03-08",
     d:"Sender veröffentlichen Ereignisse, ohne die Empfänger zu kennen; beliebig viele Empfänger können abonnieren – lose gekoppelt.",
     d_en:"Publishers emit events without knowing the receivers; any number of subscribers can subscribe – loosely coupled.",
     m:"Veröffentlichen statt gezielt aufrufen.", m_en:"Publish instead of calling directly.",
     ex:"z. B. „BestellungAufgegeben“-Event, das Versand und Rechnung abonnieren.", ex_en:"e.g. an „OrderPlaced“ event subscribed to by shipping and invoicing." },
   { t:"Client-Server", t_en:"Client-server", r:"R3", lz:"03-08",
     d:"Anfragende Clients nutzen Dienste eines bereitstellenden Servers über eine definierte Schnittstelle.",
     d_en:"Requesting clients use services of a providing server over a defined interface.",
     m:"Client fragt, Server liefert.", m_en:"Client asks, server serves.",
     ex:"z. B. Browser (Client) ↔ Webserver.", ex_en:"e.g. browser (client) ↔ web server." },
   { t:"SOA", t_en:"SOA", r:"R3", lz:"03-08",
     d:"„Service-Oriented Architecture“: fachliche Funktionen werden als wiederverwendbare, lose gekoppelte Dienste bereitgestellt (oft unternehmensweit).",
     d_en:"„Service-Oriented Architecture“: business functions provided as reusable, loosely coupled services (often enterprise-wide).",
     m:"Fachfunktionen als wiederverwendbare Dienste.", m_en:"Business functions as reusable services.",
     ex:"z. B. ein unternehmensweiter „Kundendaten“-Dienst.", ex_en:"e.g. an enterprise-wide „customer data“ service." },
   { t:"Plugin", t_en:"Plugin", r:"R3", lz:"03-08",
     d:"Ein Kern wird über definierte Erweiterungspunkte um austauschbare Zusatzmodule erweitert, ohne den Kern zu ändern.",
     d_en:"A core is extended via defined extension points with interchangeable add-on modules, without changing the core.",
     m:"Kern + einsteckbare Erweiterungen.", m_en:"Core + pluggable extensions.",
     ex:"z. B. Browser- oder IDE-Erweiterungen.", ex_en:"e.g. browser or IDE extensions." },
   { t:"Dependency Injection", t_en:"Dependency injection", r:"R3", lz:"03-08",
     d:"Abhängigkeiten werden einem Baustein von außen hineingegeben, statt dass er sie selbst erzeugt – externalisiert Abhängigkeiten, senkt Kopplung.",
     d_en:"Dependencies are handed to a building block from outside instead of it creating them – externalizes dependencies, lowers coupling.",
     m:"Abhängigkeiten reingeben, nicht selbst erzeugen.", m_en:"Hand in dependencies, don't create them.",
     ex:"z. B. der Service bekommt sein Repository im Konstruktor übergeben.", ex_en:"e.g. the service receives its repository via the constructor." }
  ]},
  { cat:"Vorgehen & Methoden", cat_en:"Approaches & methods", terms:[
   { t:"Top-down", t_en:"Top-down", r:"R1", lz:"03-03",
     d:"Vom Groben ins Feine entwerfen: erst die großen Bausteine, dann schrittweise verfeinern.",
     d_en:"Design from coarse to fine: start with the large building blocks, then refine step by step.",
     m:"Erst das große Ganze, dann Details.", m_en:"Big picture first, then details.",
     ex:"z. B. erst Subsysteme festlegen, dann deren Innenleben.", ex_en:"e.g. define subsystems first, then their internals." },
   { t:"Bottom-up", t_en:"Bottom-up", r:"R1", lz:"03-03",
     d:"Aus vorhandenen Details/Bausteinen größere Strukturen zusammensetzen.",
     d_en:"Assemble larger structures from existing details/building blocks.",
     m:"Aus kleinen Teilen Größeres bauen.", m_en:"Build larger things from small parts.",
     ex:"z. B. aus bestehenden Bibliotheken ein Subsystem formen.", ex_en:"e.g. form a subsystem from existing libraries." },
   { t:"Sichtenbasiertes Vorgehen", t_en:"View-based approach", r:"R1", lz:"03-03",
     d:"Die Architektur wird über verschiedene Sichten (Baustein-, Laufzeit-, Verteilungssicht) schrittweise erarbeitet.",
     d_en:"The architecture is developed step by step via different views (building block, runtime, deployment).",
     m:"Über die Sichten entwerfen.", m_en:"Design through the views.",
     ex:"z. B. abwechselnd Bausteinsicht und Laufzeitsicht verfeinern.", ex_en:"e.g. refine building block and runtime views alternately." },
   { t:"Iteratives Vorgehen", t_en:"Iterative approach", r:"R1", lz:"03-05",
     d:"Entwurf in Zyklen: entscheiden, umsetzen, Rückmeldung einholen, verfeinern – statt alles vorab final festzulegen.",
     d_en:"Design in cycles: decide, implement, gather feedback, refine – instead of fixing everything upfront.",
     m:"In Schleifen entwerfen, nicht in einem Rutsch.", m_en:"Design in loops, not in one shot.",
     ex:"z. B. tragende Entscheidung per Prototyp früh gegen Risiken absichern.", ex_en:"e.g. de-risk a load-bearing decision early via a prototype." },
   { t:"Domain-Driven Design (DDD)", t_en:"Domain-driven design (DDD)", r:"R3", lz:"03-03",
     d:"Entwurf orientiert sich eng an der Fachdomäne; zentrale Begriffe: Bounded Context, Ubiquitous Language.",
     d_en:"Design closely follows the business domain; key terms: bounded context, ubiquitous language.",
     m:"Struktur folgt der Fachdomäne.", m_en:"Structure follows the business domain.",
     ex:"z. B. „Versand“ und „Abrechnung“ als getrennte Bounded Contexts.", ex_en:"e.g. „shipping“ and „billing“ as separate bounded contexts." },
   { t:"Evolutionäre Architektur", t_en:"Evolutionary architecture", r:"R3", lz:"03-05",
     d:"Architektur, die bewusst auf laufende Veränderung ausgelegt ist und über Fitness-Funktionen abgesichert wird.",
     d_en:"Architecture deliberately designed for ongoing change, guarded by fitness functions.",
     m:"Auf Wandel ausgelegt, per Fitness-Funktion überwacht.", m_en:"Built for change, guarded by fitness functions.",
     ex:"z. B. automatisierte Regel „UI darf nicht auf DB zugreifen“ im Build.", ex_en:"e.g. an automated rule „UI must not access the DB“ in the build." },
   { t:"Globale Analyse", t_en:"Global analysis", r:"R3", lz:"03-03",
     d:"Systematisches Erfassen und Bewerten der Einflussfaktoren (Organisation, Technik, Produkt) vor dem Entwurf.",
     d_en:"Systematically capturing and assessing influencing factors (organizational, technical, product) before design.",
     m:"Erst Einflussfaktoren sammeln, dann entwerfen.", m_en:"Gather influencing factors first, then design.",
     ex:"z. B. frühzeitig Randbedingungen wie „nur Cloud X erlaubt“ erheben.", ex_en:"e.g. capture constraints like „only cloud X allowed“ early." }
  ]},
  { cat:"Anforderungen & Qualität", cat_en:"Requirements & quality", terms:[
   { t:"Funktionale Anforderung", t_en:"Functional requirement", r:"R1", lz:"02-02",
     d:"Beschreibt, WAS das System fachlich leisten soll (eine konkrete Funktion/Fähigkeit).",
     d_en:"Describes WHAT the system should do functionally (a concrete function/capability).",
     m:"Was das System tun soll.", m_en:"What the system should do.",
     ex:"z. B. „Nutzer kann eine Rechnung als PDF exportieren“.", ex_en:"e.g. „a user can export an invoice as PDF“." },
   { t:"Qualitätsanforderung", t_en:"Quality requirement", r:"R1", lz:"02-02",
     d:"Beschreibt, WIE GUT das System etwas tun soll (Performanz, Sicherheit, Wartbarkeit …). Prägt die Architektur oft stärker als die Funktionen.",
     d_en:"Describes HOW WELL the system should do something (performance, security, maintainability …). Often shapes architecture more than functions.",
     m:"Wie gut – der eigentliche Architektur-Treiber.", m_en:"How well – the real architecture driver.",
     ex:"z. B. „Antwort in unter 2 Sekunden bei 1000 Nutzern“.", ex_en:"e.g. „response under 2 seconds with 1000 users“." },
   { t:"Randbedingung", t_en:"Constraint", r:"R1", lz:"02-02",
     d:"Eine Vorgabe, die den Lösungsraum einschränkt (Technologie, Budget, Normen, Team-Struktur). Keine Anforderung, aber zu berücksichtigen.",
     d_en:"A given that limits the solution space (technology, budget, standards, team). Not a requirement, but to be respected.",
     m:"Vorgabe, die den Lösungsraum begrenzt.", m_en:"A given that limits the solution space.",
     ex:"z. B. „muss die vorhandene Oracle-DB nutzen“.", ex_en:"e.g. „must use the existing Oracle DB“." },
   { t:"Anliegen (Concern)", t_en:"Concern", r:"R1", lz:"02-01",
     d:"Ein Interesse eines Stakeholders am System. Nicht jedes Anliegen wird zur Anforderung, aber jedes ist zu berücksichtigen.",
     d_en:"A stakeholder's interest in the system. Not every concern becomes a requirement, but each must be considered.",
     m:"Interesse eines Stakeholders (≠ Anforderung).", m_en:"A stakeholder's interest (≠ requirement).",
     ex:"z. B. Betrieb: „muss ohne Downtime deploybar sein“.", ex_en:"e.g. operations: „must be deployable without downtime“." },
   { t:"Stakeholder", t_en:"Stakeholder", r:"R1", lz:"02-01",
     d:"Jede Person/Rolle mit berechtigtem Interesse am System (Entwicklung, Betrieb, PO, Management, QS …).",
     d_en:"Any person/role with a legitimate interest in the system (development, operations, PO, management, QA …).",
     m:"Wer ein Interesse am System hat.", m_en:"Anyone with an interest in the system.",
     ex:"z. B. Product Owner, Betriebsteam, Datenschutzbeauftragte.", ex_en:"e.g. product owner, operations team, data protection officer." },
   { t:"Qualitätsszenario", t_en:"Quality scenario", r:"R1", lz:"02-04",
     d:"Macht eine Qualitätsanforderung messbar über vier Teile: Kontext, Stimulus (Auslöser), Reaktion, Messung.",
     d_en:"Makes a quality requirement measurable via four parts: context, stimulus, response, measurement.",
     m:"Kontext · Stimulus · Reaktion · Messung.", m_en:"Context · stimulus · response · measurement.",
     ex:"z. B. „bei 1000 parallelen Anfragen (Stimulus) antwortet das System in < 2 s (Messung)“.", ex_en:"e.g. „with 1000 concurrent requests (stimulus) the system responds in < 2 s (measurement)“." },
   { t:"Qualitätsmodell (ISO/IEC 25010)", t_en:"Quality model (ISO/IEC 25010)", r:"R1", lz:"02-03",
     d:"Eine Taxonomie von Qualitätsmerkmalen (Zuverlässigkeit, Wartbarkeit, Sicherheit …). Man muss kein Modell auswendig können, aber wissen, dass Qualitäten geordnet werden.",
     d_en:"A taxonomy of quality attributes (reliability, maintainability, security …). You need not memorize a model, but know qualities are organized.",
     m:"Geordneter Katalog der Qualitätsmerkmale.", m_en:"An ordered catalogue of quality attributes.",
     ex:"z. B. „Wartbarkeit“ mit Untermerkmalen wie Analysierbarkeit, Änderbarkeit.", ex_en:"e.g. „maintainability“ with sub-attributes like analysability, modifiability." },
   { t:"Trade-off (Zielkonflikt)", t_en:"Trade-off", r:"R1", lz:"02-03",
     d:"Qualitäten stehen oft in Konkurrenz (z. B. Sicherheit ↔ Benutzbarkeit). Architektur heißt bewusst abwägen, nicht alles gleichzeitig maximieren.",
     d_en:"Qualities often compete (e.g. security ↔ usability). Architecture means deliberately weighing, not maximizing everything at once.",
     m:"Man kann nicht alles gleichzeitig haben.", m_en:"You can't have everything at once.",
     ex:"z. B. mehr Sicherheit (2FA) senkt die Benutzbarkeit.", ex_en:"e.g. more security (2FA) lowers usability." },
   { t:"Referenzarchitektur", t_en:"Reference architecture", r:"R1", lz:"02-02",
     d:"Eine bewährte, vorgegebene Architekturvorlage für eine Domäne/Technologie, an der man sich orientiert (kann Randbedingung sein).",
     d_en:"A proven, prescribed architecture template for a domain/technology used as guidance (can be a constraint).",
     m:"Blaupause statt bei null anzufangen.", m_en:"A blueprint instead of starting from scratch.",
     ex:"z. B. eine unternehmensweite Vorlage für Microservice-Aufbau.", ex_en:"e.g. a company-wide template for microservice setups." },
   { t:"Produkt- vs. Summentyp", t_en:"Product vs. sum type", r:"R2", lz:"01-07",
     d:"Produkttyp = „UND“ (mehrere Felder gleichzeitig, z. B. Record). Summentyp = „ODER“ (genau eine von mehreren Alternativen). Bestimmt, welche Zustände darstellbar sind.",
     d_en:"Product type = „AND“ (several fields at once, e.g. a record). Sum type = „OR“ (exactly one of several alternatives). Determines which states are representable.",
     m:"Produkt = UND, Summe = ODER.", m_en:"Product = AND, sum = OR.",
     ex:"z. B. Zahlungsart = Karte ODER Lastschrift ODER Gutschein (Summentyp).", ex_en:"e.g. payment method = card OR direct debit OR voucher (sum type)." },
   { t:"Datenmodell-Ebenen", t_en:"Data model levels", r:"R2", lz:"01-07",
     d:"Datenmodelle werden auf drei Ebenen beschrieben: konzeptionell (fachlich), logisch (technologieneutral) und physisch (konkrete Umsetzung).",
     d_en:"Data models are described on three levels: conceptual (business), logical (technology-neutral) and physical (concrete implementation).",
     m:"Konzeptionell → logisch → physisch.", m_en:"Conceptual → logical → physical.",
     ex:"z. B. „Kunde“ (konzeptionell) → Tabellenschema (logisch) → InnoDB-Tabelle (physisch).", ex_en:"e.g. „customer“ (conceptual) → table schema (logical) → InnoDB table (physical)." },
   { t:"Conway's Law", t_en:"Conway's law", r:"R2", lz:"02-02",
     d:"Die Systemstruktur spiegelt die Kommunikationsstruktur der Organisation wider. Team-Zuschnitt und Architektur beeinflussen sich gegenseitig.",
     d_en:"The system structure mirrors the organization's communication structure. Team layout and architecture influence each other.",
     m:"Du lieferst deine Org-Struktur als Software aus.", m_en:"You ship your org chart as software.",
     ex:"z. B. drei Teams → tendenziell drei Subsysteme.", ex_en:"e.g. three teams → tend to produce three subsystems." },
   { t:"Goodhart's Law", t_en:"Goodhart's law", r:"R3", lz:"02-04",
     d:"Sobald eine Kennzahl zum Ziel wird, taugt sie nicht mehr als gutes Maß – man optimiert die Zahl statt das eigentliche Ziel.",
     d_en:"Once a measure becomes a target, it stops being a good measure – people optimize the number instead of the actual goal.",
     m:"Kennzahl als Ziel entwertet die Kennzahl.", m_en:"A measure made a target ceases to measure well.",
     ex:"z. B. „Testabdeckung 100 %“ als Ziel → sinnlose Tests nur für die Quote.", ex_en:"e.g. „100 % test coverage“ as a target → pointless tests just for the number." }
  ]},
  { cat:"Notation & Diagramme", cat_en:"Notation & diagrams", terms:[
   { t:"UML", t_en:"UML", r:"R2", lz:"04-03",
     d:"Standard-Notation für Architektur-/Entwurfsdiagramme. Man muss nicht alle Diagrammarten beherrschen, aber die wichtigsten lesen können.",
     d_en:"Standard notation for architecture/design diagrams. You need not master all diagram types, but should read the main ones.",
     m:"Standardsprache für Architekturdiagramme.", m_en:"The standard language for architecture diagrams.",
     ex:"z. B. Komponenten-, Sequenz-, Verteilungsdiagramm.", ex_en:"e.g. component, sequence, deployment diagrams." },
   { t:"Klassendiagramm", t_en:"Class diagram", r:"R2", lz:"04-03",
     d:"UML-Diagramm für Typen/Klassen mit Attributen, Operationen und Beziehungen (Vererbung, Assoziation) – statische Struktur.",
     d_en:"UML diagram for types/classes with attributes, operations and relationships (inheritance, association) – static structure.",
     m:"Klassen + Beziehungen, statisch.", m_en:"Classes + relationships, static.",
     ex:"z. B. „Bestellung“ hat mehrere „Positionen“.", ex_en:"e.g. „Order“ has several „Line items“." },
   { t:"Komponentendiagramm", t_en:"Component diagram", r:"R2", lz:"04-03",
     d:"UML-Diagramm mit Bausteinen und ihren angebotenen bzw. benötigten Schnittstellen – Kern der Bausteinsicht.",
     d_en:"UML diagram with building blocks and their provided/required interfaces – core of the building block view.",
     m:"Bausteine + Schnittstellen.", m_en:"Building blocks + interfaces.",
     ex:"z. B. „Zahlungsmodul“ bietet „PayAPI“, benötigt „BankGateway“.", ex_en:"e.g. „payment module“ provides „PayAPI“, requires „BankGateway“." },
   { t:"Sequenzdiagramm", t_en:"Sequence diagram", r:"R2", lz:"04-03",
     d:"UML-Diagramm für den zeitlich geordneten Nachrichtenaustausch zwischen Beteiligten in einem Ablauf – Laufzeitsicht.",
     d_en:"UML diagram for the time-ordered message exchange between participants in a flow – runtime view.",
     m:"Wer schickt wann welche Nachricht?", m_en:"Who sends which message when?",
     ex:"z. B. Ablauf „Login“ zwischen Browser, Server, DB.", ex_en:"e.g. the „login“ flow between browser, server, DB." },
   { t:"Verteilungsdiagramm", t_en:"Deployment diagram", r:"R2", lz:"04-03",
     d:"UML-Diagramm, das Software-Artefakte den Hardware-/Ausführungsknoten zuordnet – Verteilungssicht.",
     d_en:"UML diagram mapping software artifacts onto hardware/execution nodes – deployment view.",
     m:"Artefakte auf Knoten.", m_en:"Artifacts on nodes.",
     ex:"z. B. „app.jar“ läuft auf „AppServer1“ und „AppServer2“.", ex_en:"e.g. „app.jar“ runs on „AppServer1“ and „AppServer2“." },
   { t:"Aktivitätsdiagramm", t_en:"Activity diagram", r:"R2", lz:"04-03",
     d:"UML-Diagramm für Abläufe/Workflows mit Aktionen, Verzweigungen und Parallelität.",
     d_en:"UML diagram for flows/workflows with actions, branches and parallelism.",
     m:"Ablauf mit Verzweigungen (wie ein Flussdiagramm).", m_en:"A flow with branches (like a flowchart).",
     ex:"z. B. Genehmigungs-Workflow mit Ja/Nein-Verzweigung.", ex_en:"e.g. an approval workflow with a yes/no branch." },
   { t:"Zustandsdiagramm", t_en:"State diagram", r:"R3", lz:"04-03",
     d:"UML-Diagramm für die Zustände eines Objekts und die Übergänge dazwischen.",
     d_en:"UML diagram for the states of an object and the transitions between them.",
     m:"Zustände + Übergänge.", m_en:"States + transitions.",
     ex:"z. B. Bestellung: offen → bezahlt → versandt.", ex_en:"e.g. order: open → paid → shipped." },
   { t:"C4-Modell", t_en:"C4 model", r:"R3", lz:"04-03",
     d:"Vier Zoomstufen für Architekturdiagramme: Context, Container, Component, Code (Simon Brown). Pragmatisch und beliebt.",
     d_en:"Four zoom levels for architecture diagrams: Context, Container, Component, Code (Simon Brown). Pragmatic and popular.",
     m:"Context → Container → Component → Code.", m_en:"Context → Container → Component → Code.",
     ex:"z. B. vom Systemüberblick bis zum einzelnen Baustein zoomen.", ex_en:"e.g. zoom from the system overview down to a single building block." },
   { t:"ArchiMate", t_en:"ArchiMate", r:"R3", lz:"04-03",
     d:"Notation für Enterprise-Architektur über Business-, Anwendungs- und Technikebene.",
     d_en:"Notation for enterprise architecture across the business, application and technology layers.",
     m:"Enterprise-Notation über drei Ebenen.", m_en:"Enterprise notation across three layers.",
     ex:"z. B. Geschäftsprozess → Anwendung → Infrastruktur verknüpfen.", ex_en:"e.g. link business process → application → infrastructure." },
   { t:"SysML", t_en:"SysML", r:"R3", lz:"04-03",
     d:"UML-Erweiterung für Systems Engineering (auch Hardware und Anforderungen).",
     d_en:"A UML extension for systems engineering (also hardware and requirements).",
     m:"UML für ganze Systeme, nicht nur Software.", m_en:"UML for whole systems, not only software.",
     ex:"z. B. Modellierung eines eingebetteten Systems inkl. Sensorik.", ex_en:"e.g. modeling an embedded system incl. sensors." },
   { t:"ERD", t_en:"ERD", r:"R3", lz:"04-03",
     d:"Entity-Relationship-Diagramm: Datenmodell aus Entitäten und ihren Beziehungen.",
     d_en:"Entity-Relationship Diagram: a data model of entities and their relationships.",
     m:"Entitäten + Beziehungen (Datenmodell).", m_en:"Entities + relationships (data model).",
     ex:"z. B. Kunde 1—n Bestellung.", ex_en:"e.g. Customer 1—n Order." },
   { t:"BPMN", t_en:"BPMN", r:"R3", lz:"04-03",
     d:"Notation für Geschäftsprozesse und Abläufe (Business Process Model and Notation).",
     d_en:"Notation for business processes and flows (Business Process Model and Notation).",
     m:"Standard für Geschäftsprozess-Diagramme.", m_en:"The standard for business-process diagrams.",
     ex:"z. B. Bestell- und Freigabeprozess über Abteilungen.", ex_en:"e.g. an order and approval process across departments." }
  ]},
  { cat:"Dokumentation", cat_en:"Documentation", terms:[
   { t:"arc42", t_en:"arc42", r:"R3", lz:"04-09",
     d:"Ein bewährtes, frei verfügbares Template mit zwölf Abschnitten zur Dokumentation von Softwarearchitekturen.",
     d_en:"A proven, freely available template with twelve sections for documenting software architectures.",
     m:"12-Abschnitte-Vorlage für Architektur-Doku.", m_en:"A twelve-section template for architecture docs.",
     ex:"z. B. Abschnitte wie Kontextabgrenzung, Bausteinsicht, Entscheidungen.", ex_en:"e.g. sections like context, building block view, decisions." },
   { t:"ADR (Architecture Decision Record)", t_en:"ADR (architecture decision record)", r:"R2", lz:"04-08",
     d:"Hält je Entscheidung kompakt fest: Kontext, Entscheidung, Status, Konsequenzen und Alternativen. Wert liegt in Begründung und verworfenen Alternativen.",
     d_en:"Records each decision compactly: context, decision, status, consequences and alternatives. Value lies in the rationale and rejected alternatives.",
     m:"Kontext · Entscheidung · Status · Konsequenzen · Alternativen.", m_en:"Context · decision · status · consequences · alternatives.",
     ex:"z. B. „Warum Message-Broker statt REST?“ dauerhaft festhalten.", ex_en:"e.g. record „why a message broker instead of REST?“ permanently." },
   { t:"ISO/IEC/IEEE 42010", t_en:"ISO/IEC/IEEE 42010", r:"R3", lz:"04-09",
     d:"Standard mit Konzepten und Begriffen der Architekturbeschreibung (Stakeholder, Concerns, Viewpoints/Views).",
     d_en:"Standard with concepts and terms for architecture description (stakeholders, concerns, viewpoints/views).",
     m:"Begriffsrahmen für Architekturbeschreibung.", m_en:"A terminology framework for architecture description.",
     ex:"z. B. definiert, was „Sicht“ und „Viewpoint“ bedeuten.", ex_en:"e.g. defines what „view“ and „viewpoint“ mean." }
  ]},
  { cat:"Analyse & Bewertung", cat_en:"Analysis & evaluation", terms:[
   { t:"Szenariobasierte Analyse", t_en:"Scenario-based analysis", r:"R1", lz:"05-02",
     d:"Bewertung der Architektur anhand konkreter Qualitätsszenarien – prüft, wie gut der Entwurf priorisierte Qualitätsziele erreicht.",
     d_en:"Evaluating the architecture against concrete quality scenarios – checks how well the design meets prioritized quality goals.",
     m:"Architektur gegen konkrete Szenarien prüfen.", m_en:"Test the architecture against concrete scenarios.",
     ex:"z. B. „Ausfall eines Servers“ durchspielen und Reaktion bewerten.", ex_en:"e.g. play through „one server fails“ and assess the response." },
   { t:"ATAM", t_en:"ATAM", r:"R3", lz:"05-02",
     d:"„Architecture Tradeoff Analysis Method“: szenariobasierte, überwiegend qualitative Methode, die Architekturentscheidungen bewertet und Trade-offs sichtbar macht.",
     d_en:"„Architecture Tradeoff Analysis Method“: a scenario-based, mostly qualitative method that evaluates decisions and reveals trade-offs.",
     m:"Szenariobasierte Trade-off-Bewertung mit Stakeholdern.", m_en:"Scenario-based trade-off evaluation with stakeholders.",
     ex:"z. B. moderierter Workshop, der Sensitivitäts- und Trade-off-Punkte findet.", ex_en:"e.g. a facilitated workshop that finds sensitivity and trade-off points." },
   { t:"Kosten-Nutzen-Analyse (CBAM)", t_en:"Cost-benefit analysis (CBAM)", r:"R3", lz:"05-02",
     d:"Erweitert die szenariobasierte Bewertung um die wirtschaftliche Sicht: Nutzen und Kosten von Architekturentscheidungen abwägen.",
     d_en:"Extends scenario-based evaluation with the economic view: weighing the benefit and cost of architecture decisions.",
     m:"Bewertung mit Euro-Brille.", m_en:"Evaluation through an economic lens.",
     ex:"z. B. lohnt sich der Aufwand für Redundanz gegenüber dem Ausfallrisiko?", ex_en:"e.g. is the effort for redundancy worth it vs. the outage risk?" },
   { t:"Kopplungsmetrik", t_en:"Coupling metric", r:"R1", lz:"05-02",
     d:"Quantitative Kennzahl für Abhängigkeiten, z. B. Anzahl ein-/ausgehender Abhängigkeiten (afferent/efferent) eines Bausteins.",
     d_en:"A quantitative measure of dependencies, e.g. the number of incoming/outgoing dependencies (afferent/efferent) of a block.",
     m:"Abhängigkeiten zählen und bewerten.", m_en:"Count and assess dependencies.",
     ex:"z. B. ein Modul mit 30 ausgehenden Abhängigkeiten fällt negativ auf.", ex_en:"e.g. a module with 30 outgoing dependencies stands out negatively." },
   { t:"Zyklomatische Komplexität", t_en:"Cyclomatic complexity", r:"R2", lz:"05-02",
     d:"Metrik für die Anzahl linear unabhängiger Pfade durch den Kontrollfluss – im Wesentlichen durch die Verzweigungen bestimmt.",
     d_en:"A metric for the number of linearly independent paths through the control flow – essentially the branches.",
     m:"Wie viele Verzweigungswege durch den Code?", m_en:"How many branch paths through the code?",
     ex:"z. B. viele verschachtelte if/else → hohe Komplexität, schwer testbar.", ex_en:"e.g. many nested if/else → high complexity, hard to test." },
   { t:"Sensitivitätspunkt", t_en:"Sensitivity point", r:"R3", lz:"05-02",
     d:"Eine Entscheidung/Eigenschaft, die für genau ein Qualitätsmerkmal besonders ausschlaggebend ist.",
     d_en:"A decision/property that is particularly decisive for exactly one quality attribute.",
     m:"Stellschraube für EIN Qualitätsmerkmal.", m_en:"A lever for ONE quality attribute.",
     ex:"z. B. Cache-Größe entscheidet stark über die Performance.", ex_en:"e.g. cache size strongly determines performance." },
   { t:"Trade-off-Punkt", t_en:"Trade-off point", r:"R3", lz:"05-02",
     d:"Eine Entscheidung/Eigenschaft, die mehrere Qualitätsmerkmale gegensätzlich beeinflusst (Sensitivitätspunkt für mehrere Qualitäten).",
     d_en:"A decision/property that affects several quality attributes in opposing ways (a sensitivity point for several qualities).",
     m:"Eine Stellschraube, die Qualitäten gegeneinander bewegt.", m_en:"One lever moving qualities against each other.",
     ex:"z. B. Verschlüsselung erhöht Sicherheit, senkt aber Performance.", ex_en:"e.g. encryption raises security but lowers performance." },
   { t:"Architekturerosion", t_en:"Architecture erosion", r:"R2", lz:"05-03",
     d:"Das schleichende Abweichen der tatsächlichen Implementierung von der geplanten Architektur, wenn Verstöße unbemerkt bleiben.",
     d_en:"The gradual drift of the actual implementation away from the intended architecture when violations go unnoticed.",
     m:"Code driftet unbemerkt von der Soll-Architektur weg.", m_en:"Code silently drifts from the intended architecture.",
     ex:"z. B. die UI greift „nur mal schnell“ direkt auf die DB zu.", ex_en:"e.g. the UI accesses the DB directly „just quickly“." },
   { t:"Fitness-Funktion", t_en:"Fitness function", r:"R2", lz:"05-03",
     d:"Ein automatisierter Test, der eine Architekturregel dauerhaft überwacht (Idee der evolutionären Architektur).",
     d_en:"An automated test that continuously monitors an architecture rule (idea of evolutionary architecture).",
     m:"Automatischer Wächter für eine Architekturregel.", m_en:"An automated guard for an architecture rule.",
     ex:"z. B. Build bricht ab, wenn eine verbotene Abhängigkeit auftaucht.", ex_en:"e.g. the build fails if a forbidden dependency appears." },
   { t:"Konformität (Soll-Ist)", t_en:"Conformance (target/actual)", r:"R2", lz:"05-03",
     d:"Prüfung, ob die umgesetzte (Ist-)Architektur zur beabsichtigten (Soll-)Architektur passt – am zuverlässigsten per statischer Abhängigkeitsanalyse.",
     d_en:"Checking whether the implemented (actual) architecture matches the intended (target) architecture – most reliably via static dependency analysis.",
     m:"Passt der Code noch zum Plan?", m_en:"Does the code still match the plan?",
     ex:"z. B. Tool prüft, dass keine Schicht eine höhere aufruft.", ex_en:"e.g. a tool checks that no layer calls a higher one." },
   { t:"Inspektion", t_en:"Inspection", r:"R3", lz:"05-02",
     d:"Die formalste Review-Form: mit Vorbereitung, definierten Rollen, Protokoll und unabhängigem Moderator.",
     d_en:"The most formal review form: with preparation, defined roles, minutes and an independent moderator.",
     m:"Das formalste Review.", m_en:"The most formal kind of review.",
     ex:"z. B. formale Inspektion eines sicherheitskritischen Entwurfs.", ex_en:"e.g. a formal inspection of a safety-critical design." },
   { t:"Produktrisiko", t_en:"Product risk", r:"R2", lz:"05-02",
     d:"Risiko, dass das Produkt Qualitätsziele verfehlt. Aus Architektursicht mindert man es meist, indem man die Eintrittswahrscheinlichkeit senkt.",
     d_en:"The risk that the product misses quality goals. Architecturally, it is usually mitigated by lowering the probability of occurrence.",
     m:"Gefahr, dass Qualitätsziele verfehlt werden.", m_en:"The danger of missing quality goals.",
     ex:"z. B. Performance-Risiko früh per Lasttest-Prototyp senken.", ex_en:"e.g. lower a performance risk early via a load-test prototype." }
  ]},
  { cat:"Verteilte Systeme & Betrieb", cat_en:"Distributed systems & operations", terms:[
   { t:"CAP-Theorem", t_en:"CAP theorem", r:"R3", lz:"03-12",
     d:"Bei einer Netzwerkpartition (P) muss man zwischen Konsistenz (C) und Verfügbarkeit (A) abwägen – nicht alle drei gleichzeitig voll.",
     d_en:"During a network partition (P) you trade off consistency (C) against availability (A) – not all three fully at once.",
     m:"Bei Partition: Konsistenz ODER Verfügbarkeit.", m_en:"On partition: consistency OR availability.",
     ex:"z. B. verteilte DB antwortet lieber (A) mit evtl. veralteten Daten statt gar nicht.", ex_en:"e.g. a distributed DB prefers to answer (A) with possibly stale data rather than not at all." },
   { t:"ACID vs. BASE", t_en:"ACID vs. BASE", r:"R3", lz:"03-10",
     d:"ACID betont strikte Konsistenz (klassisch relational); BASE bevorzugt Verfügbarkeit und eventuelle Konsistenz (häufig NoSQL).",
     d_en:"ACID emphasizes strict consistency (classic relational); BASE favours availability and eventual consistency (often NoSQL).",
     m:"ACID = streng konsistent, BASE = eventuell konsistent.", m_en:"ACID = strictly consistent, BASE = eventually consistent.",
     ex:"z. B. Bankbuchung (ACID) vs. Social-Media-Feed (BASE).", ex_en:"e.g. a bank transfer (ACID) vs. a social-media feed (BASE)." },
   { t:"Split-Brain", t_en:"Split-brain", r:"R3", lz:"03-12",
     d:"Nach einer Partition arbeiten getrennte Teile eines verteilten Systems unabhängig weiter und geraten in einen widersprüchlichen Zustand.",
     d_en:"After a partition, separated parts of a distributed system keep working independently and end up in a contradictory state.",
     m:"Getrennte Knoten, widersprüchlicher Zustand.", m_en:"Separated nodes, contradictory state.",
     ex:"z. B. zwei Knoten halten sich beide für den „Master“.", ex_en:"e.g. two nodes both consider themselves the „master“." },
   { t:"Resilienz", t_en:"Resilience", r:"R3", lz:"03-10",
     d:"Widerstandsfähigkeit gegen Fehler und Ausfälle; erreicht u. a. durch Muster wie Timeout, Retry, Circuit Breaker.",
     d_en:"Robustness against faults and outages; achieved e.g. via patterns like timeout, retry, circuit breaker.",
     m:"Robust trotz Teilausfällen.", m_en:"Robust despite partial failures.",
     ex:"z. B. Circuit Breaker kappt Aufrufe an einen ausgefallenen Dienst.", ex_en:"e.g. a circuit breaker cuts calls to a failed service." },
   { t:"Deployment", t_en:"Deployment", r:"R3", lz:"03-11",
     d:"Prozess, um neue oder aktualisierte Software bereitzustellen. Prinzipien: Automatisierung, wiederholbare Builds, konsistente Umgebungen, leichtes Rollback.",
     d_en:"The process of making new or updated software available. Principles: automation, repeatable builds, consistent environments, easy rollback.",
     m:"Software ausliefern – automatisiert und rücknehmbar.", m_en:"Ship software – automated and reversible.",
     ex:"z. B. per Pipeline auf Knopfdruck ausrollen und bei Fehler zurückrollen.", ex_en:"e.g. roll out via pipeline at the push of a button and roll back on error." },
   { t:"CI/CD", t_en:"CI/CD", r:"R3", lz:"03-11",
     d:"Continuous Integration/Delivery: automatisiertes Bauen, Testen und Ausliefern bei jeder Änderung – kurze, sichere Releasezyklen.",
     d_en:"Continuous Integration/Delivery: automated building, testing and delivering on every change – short, safe release cycles.",
     m:"Jede Änderung automatisch bauen, testen, ausliefern.", m_en:"Automatically build, test and ship every change.",
     ex:"z. B. Merge → Pipeline testet und deployt automatisch nach Staging.", ex_en:"e.g. merge → the pipeline tests and deploys to staging automatically." }
  ]}
 ]
};
